### ISSUE TITLE
Produce 'Paths' class to same directory as model files

### ISSUE THREAD

**Issue by hiddenalpha** [swisspush/apikana-java#1]
This issues origin is https://jira.post.ch/browse/ISAGD-4674

Its somewhat confusing that generated _Paths_ class resides in another directory than the generated model files.

While Model files going into `target/java-gen/`, _Paths_ seems to go to `target/api/model/java/`.

I think it would be a good idea to use same directory for both. As i understand, @lbovet has this oppinion too.

**Comment by nidi3** [comment]
I see the issue, but
- the layout of `target` is an implementation detail 
- `Paths` is generated by apikana (the node module) which generates everything into `model/*`, e.g. `model/json-schema-v3` etc. so using a different dir would be confusing there

Maybe the question should be why the node module generates java files and not apikana-java.

**Comment by lbovet** [comment]
The layout of target/ will be relevant when we provide a distributable version of the API as zip. It will be easy to simply zip the api/ folder, so the classes should better go elsewhere. This is about implementation, though, I agree. Just something we may think about once we have fixed the two other main issues (object reuse and inheritance)

**Comment by nidi3** [comment]
As the distributable version takes care of this, I close this issue
